# -*- coding: utf-8 -*-
"""flask app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aer1auBv7k51RvVux1c-q2mNpem3I1U3
"""

pip install gevent

from __future__ import division, print_function
import sys
import os
import glob
import re
import numpy as np
from keras.models import load_model
from keras.preprocessing import image

from flask import Flask, redirect, url_for, request
from werkzeug.utils import secure_filename

# Define a flask app
app = Flask(__name__)

# Model saved with Keras model.save()
MODEL_PATH = '/content/plantdiseasedetection.h5'

# Load your trained model
model = load_model(MODEL_PATH)
model.make_predict_function()




def model_predict(img_path, model):
    img = image.load_img(img_path, target_size=(256, 256))

    # Preprocessing the image
    x = image.img_to_array(img)
    # x = np.true_divide(x, 255)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x, mode='caffe')

    preds = model.predict(x)
    return preds




@app.route('/predict', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST':
        # Get the file from post request
        f = request.files['file']

        # Save the file to ./uploads
        basepath = os.path.dirname(__file__)
        file_path = os.path.join(
            basepath, 'uploads', secure_filename(f.filename))
        f.save(file_path)

        # Make prediction
        preds = model.predict(file_path, model)

        pred_class = decode_predictions(preds, top=1)   
        result = str(pred_class[0][0][1])               
        return result
    return None


import portpicker
port = portpicker.pick_unused_port()
from google.colab import output
output.serve_kernel_port_as_window(port)

from gevent.pywsgi import WSGIServer
host='localhost'
app_server = WSGIServer((host, port), app)
app_server.serve_forever()

# Commented out IPython magic to ensure Python compatibility.
# %tb
